### ISSUE TITLE
[SPEC] Handle long-living unsigned proposals and remove from runtime to prevent unchecked state growth

### ISSUE THREAD

**Issue by drewstone** [webb-tools/dkg-substrate#298] opened 2022-04-29 16:00 UTC
# Overview 

If the DKG fails to work for some reason, we should have a plan for automatically cleaning out the unsigned proposal queue. This can be done by storing the block number when the unsigned proposal is added and cleaning the storage when it is outdated with some configuration parameter / limit.

## Examples 

# Questions/Issues

**Comment by 1xstj** [comment] 2022-06-03 21:05
Duplicate of #307

**Comment by 1xstj** [comment] 2022-06-07 06:51
Also closed by #312

**Closed by 1xstj** 2022-06-07 06:51 UTC
Labels: spec 🆕
